### ISSUE TITLE
Suport for Ios 

### ISSUE THREAD

**Issue by renanzdm** [Rajath4/BluetoothThermalPrinter#12]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

In the documentation it says it only works on Android but pub dev supports ios too. Could you confirm?

**Comment by programmerpie** [comment]
This SDK only available for [Android](https://pub.dev/packages/bluetooth_thermal_printer).
![issue](https://user-images.githubusercontent.com/119511688/204818787-c23ca8e8-8de0-45a2-a4cc-8fae5d3dbb29.png)

**Comment by renanzdm** [comment]
Ok, is not necessary
